version: '3'
services:
  backend:
    build: ./backendMicroservicos
    volumes:
      - ./backendMicroservicos:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      
  frontend:
    build: ./frontEndNextJs
    volumes:
      - ./frontEndNextJs:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
